.\" Manpage for pyqode-designer.
.\" Contact colin.duquesnoy@gmail.com to correct errors or typos.
.TH man 1 "07 Dec 2013" "2.0.1" "open-cobol-ide man page"
.SH NAME
pyqode-designer \- starts the IDE
.SH SYNOPSIS
pyqode-designer
.SH DESCRIPTION
Start Qt Designer with the pyqode plugins
.SH OPTIONS
pyqode-designer does not take any options or arguments.
.SH BUGS
No known bugs.
.SH AUTHOR
Colin Duquesnoy (colin.duquesnoy@gmail.com)